name: easy_drink
description: Facilita la scelta dei cocktail per un aperitivo.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  salomon_bottom_bar: ^3.1.0
  auto_route: 7.8.4
  freezed_annotation: ^2.0.3
  http: ^0.13.6
  google_fonts: ^4.0.1
  flutter_staggered_grid_view: ^0.4.1
  transparent_image: ^2.0.1
  sembast: ^3.1.1
  path: ^1.8.0
  path_provider: ^2.0.5
  material_floating_search_bar_2: ^0.5.0
  multi_select_flutter: ^4.1.3
  state_notifier: ^0.7.2+1
  flutter_state_notifier: ^0.7.3
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  local_auth: ^2.1.4
  flutter_localizations: 
    sdk: flutter
  settings_ui: ^2.0.2
  url_launcher: ^6.0.12
  open_settings: ^2.0.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  auto_route_generator: any
  build_runner: ^2.4.9
  freezed: ^2.0.3
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0


flutter:
  uses-material-design: true

  
  assets:
    - google_fonts/
    - assets/images/cocktail_placeholder.jpg
    - assets/images/the_cocktail_db_logo.png
    - assets/splash_logo.png
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
